language: generic
env:
  global:
    - CLI_VERSION=0.5.0
  matrix:
    - BOARD="mcci:stm32:mcci_catena_4610"
before_install:
  - sudo dnf install glibc.i686
  - wget https://github.com/arduino/arduino-cli/releases/download/0.5.0/arduino-cli_0.5.0_Linux_64bit.tar.gz
  - tar -xf arduino-cli_0.5.0_Linux_64bit.tar.gz 
  - mkdir -p $HOME/bin
  - mv arduino-cli $HOME/bin/arduino-cli
  - export PATH=$PATH:$HOME/bin
  - arduino-cli core update-index --additional-urls https://github.com/mcci-catena/arduino-boards/raw/master/BoardManagerFiles/package_mcci_index.json 
  - arduino-cli core install mcci:stm32 --additional-urls https://github.com/mcci-catena/arduino-boards/raw/master/BoardManagerFiles/package_mcci_index.json 
  - buildExampleSketch() { arduino-cli compile --verbose --warnings all --fqbn $BOARD $PWD/examples/$1; }
install:
  - mkdir -p $HOME/Arduino/libraries
  - ln -s $PWD $HOME/Arduino/libraries/.
script:
  - buildExampleSketch TransmitPacket